#!/usr/bin/env node
/**
 * WASM Inlining Utility for WebClaw Single-File Build
 *
 * This script provides functions to inline WASM binaries into HTML as base64 data URIs.
 * Supports both brotli-compressed and gzip-compressed WASM.
 *
 * Usage:
 *   import { inlineWASM, getWASMAsBase64 } from './scripts/inline-wasm.js';
 *   const base64 = getWASMAsBase64('dist/webclaw.wasm.br');
 */

import fs from "fs";
import path from "path";
import zlib from "zlib";

/**
 * Read a WASM file and return it as base64 encoded string
 * @param {string} wasmPath - Path to WASM file
 * @param {Object} options - Options for encoding
 * @param {boolean} options.compress - Whether to gzip compress before encoding
 * @returns {string} Base64 encoded WASM
 */
export function getWASMAsBase64(wasmPath, options = {}) {
  const { compress = false } = options;

  if (!fs.existsSync(wasmPath)) {
    throw new Error(`WASM file not found: ${wasmPath}`);
  }

  let wasmBuffer = fs.readFileSync(wasmPath);

  // If input is already brotli compressed, we need to decompress first
  // then re-compress with gzip for better browser support
  const ext = path.extname(wasmPath);
  if (ext === ".br") {
    console.log(`[inline-wasm] Decompressing brotli: ${wasmPath}`);
    wasmBuffer = zlib.brotliDecompressSync(wasmBuffer);
    console.log(
      `[inline-wasm] Decompressed size: ${(wasmBuffer.length / 1024 / 1024).toFixed(2)}MB`,
    );
  }

  // Compress with gzip if requested (for inline mode)
  if (compress) {
    console.log(`[inline-wasm] Compressing with gzip...`);
    wasmBuffer = zlib.gzipSync(wasmBuffer, { level: 9 });
    console.log(
      `[inline-wasm] Compressed size: ${(wasmBuffer.length / 1024).toFixed(2)}KB`,
    );
  }

  // Convert to base64
  const base64 = wasmBuffer.toString("base64");
  console.log(
    `[inline-wasm] Base64 encoded size: ${(base64.length / 1024).toFixed(2)}KB`,
  );

  return base64;
}

/**
 * Generate JavaScript code that decompresses and loads WASM from base64
 * Uses DecompressionStream API with pako fallback for older browsers
 * @param {string} base64WASM - Base64 encoded WASM (gzip compressed)
 * @returns {string} JavaScript code string
 */
export function generateWASMLoader(base64WASM) {
  // Use DecompressionStream API for modern browsers with pako fallback
  return `
// WASM Loader - Auto-generated by inline-wasm.js
(function() {
    'use strict';
    
    const __WASM_BASE64__ = "${base64WASM}";
    
    // Decode base64 to Uint8Array
    function base64ToUint8Array(base64) {
        const binaryString = atob(base64);
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
            bytes[i] = binaryString.charCodeAt(i);
        }
        return bytes;
    }
    
    // Decompress gzip using DecompressionStream API or pako
    async function decompressGzip(compressed) {
        // Try DecompressionStream API first (modern browsers)
        if (typeof DecompressionStream !== 'undefined') {
            const ds = new DecompressionStream('gzip');
            const writer = ds.writable.getWriter();
            const reader = ds.readable.getReader();
            
            // Write compressed data
            writer.write(compressed);
            writer.close();
            
            // Read decompressed data
            const chunks = [];
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                chunks.push(value);
            }
            
            // Concatenate chunks
            let totalLength = 0;
            for (const chunk of chunks) {
                totalLength += chunk.length;
            }
            const result = new Uint8Array(totalLength);
            let offset = 0;
            for (const chunk of chunks) {
                result.set(chunk, offset);
                offset += chunk.length;
            }
            return result;
        }
        
        // Fallback: use pako if available (should be included inline)
        if (typeof pako !== 'undefined') {
            return pako.inflate(compressed);
        }
        
        throw new Error('No gzip decompressor available. Please use a modern browser or include pako.');
    }
    
    // Override fetch to intercept WASM requests and return from memory
    const originalFetch = window.fetch;
    window.fetch = async function(url, options) {
        const urlStr = url.toString();
        
        // Intercept WASM requests
        if (urlStr.includes('webclaw.wasm') && !urlStr.includes('data:')) {
            console.log('[WASM Loader] Intercepting WASM fetch, serving from inline base64');
            
            try {
                // Decode and decompress
                const compressed = base64ToUint8Array(__WASM_BASE64__);
                const wasmBinary = await decompressGzip(compressed);
                
                console.log('[WASM Loader] WASM decompressed:', wasmBinary.length, 'bytes');
                
                // Return as Response object
                return new Response(wasmBinary, {
                    status: 200,
                    statusText: 'OK',
                    headers: {
                        'Content-Type': 'application/wasm',
                        'Content-Length': wasmBinary.length.toString()
                    }
                });
            } catch (err) {
                console.error('[WASM Loader] Failed to load inline WASM:', err);
                throw err;
            }
        }
        
        return originalFetch.apply(this, arguments);
    };
    
    console.log('[WASM Loader] WASM fetch interceptor installed');
})();
`.trim();
}

/**
 * Inline WASM into HTML content
 * @param {string} htmlContent - Original HTML content
 * @param {string} wasmPath - Path to WASM file
 * @returns {string} Modified HTML with inline WASM
 */
export function inlineWASM(htmlContent, wasmPath) {
  const base64 = getWASMAsBase64(wasmPath, { compress: true });
  const loaderCode = generateWASMLoader(base64);

  // Inject WASM loader before the first script tag
  const scriptMatch = htmlContent.match(/<script[^>]*>/);
  if (!scriptMatch) {
    throw new Error("No script tag found in HTML");
  }

  const injectionPoint = scriptMatch.index;
  const beforeScript = htmlContent.substring(0, injectionPoint);
  const afterScript = htmlContent.substring(injectionPoint);

  return beforeScript + `<script>${loaderCode}</script>\n` + afterScript;
}

// CLI usage
if (import.meta.url === `file://${process.argv[1]}`) {
  const args = process.argv.slice(2);
  const command = args[0];

  switch (command) {
    case "encode":
      const wasmFile = args[1] || "dist/webclaw.wasm.br";
      const outputFile = args[2];

      try {
        const base64 = getWASMAsBase64(wasmFile, { compress: true });

        if (outputFile) {
          fs.writeFileSync(outputFile, base64);
          console.log(`[inline-wasm] Base64 written to: ${outputFile}`);
        } else {
          console.log(base64);
        }
      } catch (err) {
        console.error("[inline-wasm] Error:", err.message);
        process.exit(1);
      }
      break;

    case "loader":
      const wasmFile2 = args[1] || "dist/webclaw.wasm.br";
      const outputFile2 = args[2];

      try {
        const base64 = getWASMAsBase64(wasmFile2, { compress: true });
        const loader = generateWASMLoader(base64);

        if (outputFile2) {
          fs.writeFileSync(outputFile2, loader);
          console.log(`[inline-wasm] Loader written to: ${outputFile2}`);
        } else {
          console.log(loader);
        }
      } catch (err) {
        console.error("[inline-wasm] Error:", err.message);
        process.exit(1);
      }
      break;

    default:
      console.log(`
WASM Inlining Utility

Usage:
  node inline-wasm.js encode [wasm-file] [output-file]  - Encode WASM to base64
  node inline-wasm.js loader [wasm-file] [output-file]   - Generate full loader code

Examples:
  node inline-wasm.js encode dist/webclaw.wasm.br
  node inline-wasm.js loader dist/webclaw.wasm.br wasm-loader.js
`);
  }
}
